// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05pLdrwrXpBdYO_HokL9J1LP3DF4jDcg',
    appId: '1:536957137727:web:7017133bfa4ac46af9598a',
    messagingSenderId: '536957137727',
    projectId: 'practico2-f3f38',
    authDomain: 'practico2-f3f38.firebaseapp.com',
    storageBucket: 'practico2-f3f38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-tedgx4N_c7U43ZZIyvq-l1c-RAyVMYs',
    appId: '1:536957137727:android:15d0b9d507f7bea0f9598a',
    messagingSenderId: '536957137727',
    projectId: 'practico2-f3f38',
    storageBucket: 'practico2-f3f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEBVQT5bFrJzxqGMa5_OcZLZcairc2gs',
    appId: '1:536957137727:ios:199591089161b6e1f9598a',
    messagingSenderId: '536957137727',
    projectId: 'practico2-f3f38',
    storageBucket: 'practico2-f3f38.firebasestorage.app',
    iosBundleId: 'com.example.practico2Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGEBVQT5bFrJzxqGMa5_OcZLZcairc2gs',
    appId: '1:536957137727:ios:199591089161b6e1f9598a',
    messagingSenderId: '536957137727',
    projectId: 'practico2-f3f38',
    storageBucket: 'practico2-f3f38.firebasestorage.app',
    iosBundleId: 'com.example.practico2Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB05pLdrwrXpBdYO_HokL9J1LP3DF4jDcg',
    appId: '1:536957137727:web:7f5c61fe2216df04f9598a',
    messagingSenderId: '536957137727',
    projectId: 'practico2-f3f38',
    authDomain: 'practico2-f3f38.firebaseapp.com',
    storageBucket: 'practico2-f3f38.firebasestorage.app',
  );
}
